In [1]:
#!pip install opencv-python
#!pip install pytesseract
#!pip install -U spacy

In [2]:
import matplotlib as plt
%matplotlib inline
import pandas as pd
import pytesseract 
import cv2
pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
import numpy as np
import spacy
from PIL import Image

In [19]:
import locale
locale.getpreferredencoding()


'UTF-8'

In [ ]:
#runs forever, don't run
imgdecode = cv2.imdecode(np.fromfile('/Users/lsanchez/Desktop/DIGHUM101-2020-Project/onepiece_test/onepiece_test.jpg', dtype=np.uint8), cv2.IMREAD_UNCHANGED)
#print(imgdecode)
cv2.imshow("img_decode", imgdecode)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
#!pip install opencv-contrib-python

In [3]:
#!brew install tesseract
#!pip install tesseract-ocr-jpn
#!brew list tesseract
pytesseract.pytesseract.tesseract_cmd = '/usr/local/Cellar/tesseract/4.1.1/bin/tesseract'
tessdata_dir_config = "/usr/local/Cellar/tesseract/4.1.1/bin/tesseract"

In [26]:
#reading manga page
output = pytesseract.image_to_string('/Users/lsanchez/Desktop/DIGHUM101-2020-Project/onepiece_test/onepiece_test.jpg', lang='jpn_vert', config=tessdata_dir_config)

print(output)

グル
た

Cu へ に て


In [5]:
#reads english version of manga, but does not read boxes correctly
op_eng_img=Image.open("/Users/lsanchez/Desktop/DIGHUM101-2020-Project/onepiece_test/onepiece_engtest.jpg")
op_eng_img.load()
eng_text = pytesseract.image_to_string(op_eng_img, lang = "eng")    
print(eng_text)

SURPRISINGLY,
ata yao
WORDS HE

SPOKE BEFORE
THEY LOPPED
OFF HIS HEAD

INSPIRED

AQVENTURERS

THROUGHOUT

THE WORLO TO

SAIL THE SEAS.

SS
ABOUT TO
WITNESS
)
GREAT ERA

GOLD

ROGER,

THE
WEALTH, "KING OF

FAME aries

ANO ee
power PIRATES,

HAD ALL
ott =e)
ee Tt (ill,

HIS.

 

iv

MY
TREASURE?
WHY, IT’S RIGHT
WHERE | LEFT IT...

YOURS IF YOU
CAN FINO IT...
BUT YOU'LL HAVE
TO SEARCH THE
WHOLE WORLD!

 

{My

(y)


In [41]:
#outputs decoded image
path = '/Users/lsanchez/Desktop/DIGHUM101-2020-Project/onepiece_test/onepiece_test.png'
test_img = cv2.imread(path) 
cv2.startWindowThread()
cv2.namedWindow("preview")
cv2.imshow("preview", test_img)
print(test_img)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [243 243 243]
  [250 250 250]
  [ 72  72  72]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [247 247 247]
  [235 235 235]
  [ 69  69  69]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [196 196 196]
  [235 235 235]
  [ 68  68  68]]

 ...

 [[  0   1   0]
  [  0   1   0]
  [  0   1   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  1   1   1]]

 [[  2   3   0]
  [  1   2   0]
  [  1   2   0]
  ...
  [  0   0   0]
  [ 14  14  14]
  [  3   3   3]]

 [[  1   2   0]
  [  1   2   0]
  [  1   2   0]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]]


In [25]:
#!pip install googletrans
#!pip install translate

     |████████████████████████████████| 171 kB 9.4 MB/s eta 0:00:01
     |████████████████████████████████| 137 kB 6.8 MB/s eta 0:00:01
     |████████████████████████████████| 97 kB 5.8 MB/s  eta 0:00:01
     |████████████████████████████████| 4.7 MB 13.3 MB/s eta 0:00:01
     |████████████████████████████████| 571 kB 13.5 MB/s eta 0:00:01
  Created wheel for distlib: filename=distlib-0.3.0-py3-none-any.whl size=340427 sha256=189af5da8dd0c837726796a448e2e5769e9e0ea5d8833f5ed5de51728b8809e6
  Stored in directory: /Users/lsanchez/Library/Caches/pip/wheels/a2/19/da/a15d4e2bedf3062c739b190d5cb5b7b2ecfbccb6b0d93c861b
Successfully built distlib


In [7]:
from googletrans import Translator


In [25]:
#reading whole managa page, changed to reading vertical, but program not finding all words
img = Image.open("/Users/lsanchez/Desktop/DIGHUM101-2020-Project/onepiece_test/onepiece_test.jpg")
img.load()
text = pytesseract.image_to_string(img, lang="jpn")  #Specify language to look after!

translator = Translator()
translated = translator.translate(pytesseract.image_to_string(img, lang="jpn_vert"), src = "ja", dest = "en")
print(text)
print(translated.text)

に
如

びっくりレし:
Guru
Was

To Cu


In [59]:
#reading japanese ad
#ad_img = Image.open("/Users/lsanchez/Desktop/jpn_ad.jpg")
ad_img = cv2.imread("/Users/lsanchez/Desktop/jpn_ad.jpg")
img.load()
ad_text = pytesseract.image_to_string(img, lang="jpn")  #Specify language to look after!

translator = Translator()
ad_translated = translator.translate(pytesseract.image_to_string(ad_img, lang="jpn"), src = "ja", dest = "en")
#print(ad_text)
print(ad_translated.text)

YY Sakirun

Glory pan
Fine nutrition white pavant

  
    

Yamazaki Baking Co., Ltd.

Central shops Various locations in Tokyo, Ichikawa, and Yokohama |


In [54]:
#reading japanese ad
ad = cv2.imread("/Users/lsanchez/Desktop/jpn_ad2.jpg",  
                  cv2.IMREAD_GRAYSCALE)
img.load()
ad_txt = pytesseract.image_to_string(img, lang="jpn")  #Specify language to look after!

translator = Translator()
ad_trans = translator.translate(pytesseract.image_to_string(ad, lang="jpn"), src = "ja", dest = "en")
#print(ad_text)
print(ad_trans.text)

Have you tried it yet?
Coca-Cola 4 le


In [24]:
#reading screen shot of vertical japanese text "Whole Cake Island"
ss = pytesseract.image_to_string('/Users/lsanchez/Desktop/jpn_ss.jpg', lang='jpn_vert', config=tessdata_dir_config)
print(ss)
ss_trans = translator.translate(ss)
print(ss_trans)

ホー ル
ケー キー
アイ ラン ド
Translated(src=ja, dest=en, text=Hole
Keeky
Island, pronunciation=[[]], extra_data="{'translat...")


In [75]:
initial_D_img = cv2.imread("/Users/lsanchez/Desktop/initial_D.jpg")
img.load()
d_text = pytesseract.image_to_string(initial_D_img, lang="jpn")  #Specify language to look after!

d_translated = translator.translate(d_text, src = "ja", dest = "en")
#print(ad_text)
print(d_translated.text)

Fujiwara Tofu shop (home


In [63]:
#reading initial D
initial_D = cv2.imread("/Users/lsanchez/Desktop/initial_D.jpg",  
                  cv2.IMREAD_GRAYSCALE)
img.load()
initial_D_text = pytesseract.image_to_string(initial_D, lang="jpn")  #Specify language to look after!

translator = Translator()
d_trans = translator.translate(pytesseract.image_to_string(initial_D, lang="jpn")  , dest = "en")
#print(ad_text)
print(d_trans.text)